### PR TITLE
I made it enable to choose whether to use life LEDs.

### PR DESCRIPTION
**Pull request by odaki**
Please review my change.

I made LIFE LEDs optional.
(I think it makes easy to port TWANG to another platforms.)
- New: Make it selectable whether to use LED or not.

... and I found a message issue.
- Fix: Average score message on first play.

I prepared to port TWANG to another board.
- New: New board must define pin number for LED strip.
- New: Sound device selectable

### CODE REVIEW

**Comment by bdring** [comment]
What platform are you porting it to? I have ported it to the ESP32.  Due to the features I want to add, bluetooth, wifi/web server, dual player, I am not sure it makes sense to keep the same code base.

When using TWANG in a public space, I often change the lifes per level depending on the typical player skill. That does not work to well with physical LEDs. Is there a good way to deal with this?

What are your thoughts on these topics?

**Comment by odaki** [comment]
> What platform are you porting it to?

I’ve ported it to the Teensy3.2 + PropShield.
https://github.com/odaki/TWANG/tree/port-to-teensy32
(It works well now.)

> I have ported it to the ESP32. 

That's sounds great. It is cheap and easy to obtain also in Japan.

> Due to the features I want to add, bluetooth, wifi/web server, dual player, I am not sure it makes sense to keep the same code base.

I agree with you. It is too complex to make enhancements with keeping a original code base.

> When using TWANG in a public space, I often change the lifes per level depending on the typical player skill. That does not work to well with physical LEDs. Is there a good way to deal with this?

7 seg for indicate lifes or… your modification (using strip LED  as life indicator) is the best I think.

**Comment by bdring** [comment]
Thanks for your advice.

I am going to pull in your...

- Average score fix
- LED selection option

I will hold off on board port options until later.

I will also add my changes to make the conveyor speed adjustable and some new levels. I will commit these changes later today.

**Comment by bdring** [comment]
Included all issues, except platform which which requires further thought and testing.

Thanks Odaki!

**Pull request closed without merging**
